name: artifactory build

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  second-action:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: install node js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: install dependencies
        run: npm ci

      - name: run the test command
        run: npm test

  Build-release:
    needs: second-action
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: install node js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: install dependencies
        run: npm ci

      - name: build the code
        run: npm run build

      - name: publish to artifactory
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: |
            dist
            package.json