name: artifactory build

on:
  workflow_dispatch:
  push:
    branches:
      - dev
env:
  NODE_AUTH_TOKEN: ${{ secrets.TEST }}

jobs:
  second-action:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: install node js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: install dependencies
        run: npm ci

      - name: run the test command
        run: npm test
      - name: Use token in script
        run: echo $NODE_AUTH_TOKEN

  Build-release:
    needs: second-action
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: install node js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: install dependencies
        run: npm ci

      - name: build the code
        run: npm run build
      - name: Use token in script
        run: echo $NODE_AUTH_TOKEN

      - name: publish to artifactory
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: |
            dist
            package.json
      